server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/ebac?authSource=admin&retryWrites=true&w=majority
      database: cliente
      auto-index-creation: true