server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000
spring:
  data:
    mongodb:
      uri: mongodb://adm:root@172.17.0.2:27017/ebac?authSource=admin&retryWrites=true&w=majority
      database: produto
      auto-index-creation: true