server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000
spring:
  data:
    mongodb:
      uri: mongodb://adm:root@172.17.0.2:27017/ebac?authSource=admin&retryWrites=true&w=majority
      database: vendas
      auto-index-creation: true
application:
  produtoService:
    url: http://localhost:8082
    endpointConsultarProduto: ${application.produtoService.url}/produto
  clienteService:
    url: http://localhost:8081
    endpointConsultarCliente: ${application.clienteService.url}/cliente/isCadastrado/{id}
application-version: 1.0.0